apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-sdir
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-sdir@sha256:009ac8ab403d79e557b4c1d86d0724e97fa0baf355e1841372ed6d2be71184c2
        name: my-python
        resources: {}
status: {}
